spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://127.0.0.1:5432/delivery_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect






jwt :
  headers: deliveryBackend
  secretKey: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
  expiration: 9600000
  refresh_expiration: 86400000
server:
  port: 8082
